### ISSUE TITLE
TO-DO LIST 0.11.X

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Zeviper-Gaming/HOI4-ImprovedDesigner#48]
- [x] Ajouter les `engines placements` depuis la version de spatialX
  - [x] Ajouter dans les techs
  - [x] Ajouter les descriptions 
- [x] Ajouter modificateur de -100% pour le thrust et la consommation
- [x] Adapter le coûts en IC
- [x] Ajouter les images
- [x] Ajouter les moteurs pour les airframes
- Différencier les moteur en tandem des moteurs Pull-Push ?
- Mettre les bonnes conversions de modules ( _Pas de conversion possible_ )
- [x] Desactiver le modules `engines_nb`
  - [x] Mettre une image pour le designer
- [x] Changer la catégorie du moteur pull push en `plane_engine_nose`
- [x] Ajouter moteur tandem (F223)
- [x] Ajouter empennage normal
