### ISSUE TITLE
TODO GLOBAL

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Zeviper-Gaming/HOI4-ImprovedDesigner#50]
# Pour BETA
- #35
- #27 (uniquement 1936)
- [x] Ajouter ailes rectangulaire dans les ailes en W
- [x] Ajouter fuselage classique
- #45
- [x] Modifier les nommages des parties (sous le fuselage, partie avant etc...)
- [x] Ajouter empennage normal
- [x] Empennage bi poutre requis pour empennage bi poutre
- [x] Pouvoir avoir des réservoirs de carburant dans les ailes
- Revoir les modificateur pour les modules
- [ ] Modifier les design des avions préconcues (voir MB 174 ?)
- [ ] Spécifier les calibre des armements (12mm, 20mm etc)
- [ ] Ajouter une nouvelle techs pour les constructions aéro
- [x] Ajouter des modifications de stats pour les rôles en fonction des missions
  - (+10% attaque aérienne en mission d'interception pour intercepteur)
  - Changer le rôle est gratuit en IC mais coute de l'XP
- [ ] Ajouter de nouveaux rôles 
- [ ] moteurs jet et rockets

# Plus tard et idées
- [ ] Mettre des images (et noms) personnalisé en fonction des frames pour les slots du Designer
- [ ] Changer les images pour les slots ? (Même charte graphique que Freezer ?) 
- [ ] Faire en sorte d'afficher l'image des categories d'ailes au lieu des modules dans le designer une fois le module choisi
