### ISSUE TITLE
TODO 0.12.X

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Zeviper-Gaming/HOI4-ImprovedDesigner#53]
- [x] Modifier les nommages des parties (sous le fuselage, partie avant etc...)
- [x] Vérifier les modules pour les slots nouvellement renommées
- [x] add musik for mid fuselages slots
- [x] Ajouter ailes rectangulaire dans les ailes en W
- [x] Ajouter fuselage classique
- [x] Dissocier les fuselage en 3 categories (small, large, medium)
- [x] enlever tout les modules dans les slots de fuselage pour les airframes afin de les debloquer par les fuselage correspondant
  - De cette facons on pourra personnalise comment les avions peuvent être construit en fonction du fuselage
  - [x] Rendre indisponibles le slot `mid_fuselage` lorsque le fuselage bi poutre est utilisé
  - [x] Empennage bi-poutre uniquement pour les fuselage bi-poutre
  - [x] Remettre les slot de queue au niveau des slots mid-fuselage pour les flying wings (comme les bi poutre)
- [x] Ajouter les images pour les fuselages
- #22 
- [x] Deplacer le moteurs de queue dans le "rear_fuselage"
- [x]  Mettre les stats des ailes basses effilés a 0 (ailes de base)
