### ISSUE TITLE
TODO 0.14.X

### ISSUE THREAD

**Issue by Florian-DELRIEU** [Zeviper-Gaming/HOI4-ImprovedDesigner#60]
- [x] Réduire le gain en agilité pour les `T tails` (et ajouter un coup de prod en IC)
- [x] Enlever le gain en poussée pour le `twin tail`
- [x] Ajouter les pâles dans les airframes
- [ ] Les moteurs d'ailes réduisent l'agilité
- [ ] Ajouter la possibilité de downgrader les moteurs d'un même type en conversion 

# Ajouter images
- [x] categories de moteurs
- [x] Modules de moteurs (toute techs)
- [x] Empennage classique
- [x] Hélices (x3, x5)
- [ ] Hélices (x6, x8) 
- [ ] Verifier le chemin pour les images des pâles 
- [ ] 
# Equilibrage
- [ ] Agilité atteint des valeurs abusives avec un avion endgame full equipé
- [ ] Vitesse supérieure a 1000km/h possible avec avion a piston (si full spedd upgrade)
![image](https://github.com/Zeviper-Gaming/HOI4-ImprovedDesigner/assets/47951736/6d96509b-a6ff-4e4a-88f8-e9410a6cab97)
